name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

      - name: Run application
        run: |
          . venv/bin/activate
          nohup python run.py &

      - name: Wait for the application to start
        run: |
          sleep 10  # Adjust this sleep time as needed

      - name: Ping the application
        run: |
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000)
          if [ "$RESPONSE" -eq 200 ]; then
            echo "successful"
          else
            echo "failed"
            exit 1
          fi
